import { useState } from 'react';
import type { Report } from './types';
import { UploadScreen } from './components/UploadScreen';
import { SummaryCards } from './components/SummaryCards';
import { RiskChart } from './components/RiskChart';
import { PackageTable } from './components/PackageTable';

export default function App() {
  const [report, setReport] = useState<Report | null>(null);

  function handleLoad(json: string) {
    try {
      setReport(JSON.parse(json) as Report);
    } catch {
      alert('Invalid JSON file. Please use a report.json generated by depgrave.');
    }
  }

  if (!report) return <UploadScreen onLoad={handleLoad} />;

  return (
    <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '32px 24px' }}>
      {/* header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '28px' }}>
        <div>
          <h1 style={{ fontSize: '22px', fontWeight: 700 }}>🪦 depgrave</h1>
          <div style={{ fontSize: '13px', color: '#64748b', marginTop: '4px' }}>
            {report.projectRoot} — scanned {new Date(report.scannedAt).toLocaleString()}
          </div>
        </div>
        <button
          onClick={() => setReport(null)}
          style={{
            background   : 'transparent',
            border       : '1px solid #2d2d3d',
            borderRadius : '8px',
            color        : '#64748b',
            cursor       : 'pointer',
            fontSize     : '13px',
            padding      : '8px 16px',
          }}
        >
          Load new report
        </button>
      </div>

      <SummaryCards report={report} />
      <RiskChart report={report} />
      <PackageTable packages={report.packages} />
    </div>
  );
}